[package]
name = "rcc"
version = "0.1.0"
authors = ["Hugo Laloge <hugo.laloge@gmail.com>"]
description = "Rust C compiler, done to learn rust and compilers"
license = "MIT"

[dependencies]
clap = "^2.29"
error-chain = "^0.11"
memchr = "^2"
nom = { version = "^3.2", features = ["verbose-errors"] }
